name: Deploy pages

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup common configuration
        uses: "./.github/actions/install-deps"

      # Build the project into the dist directory
      - name: Build
        run: |
          npm run build -- --base /${{github.event.repository.name}}/
          npm run package
          unzip reveal-js-presentation.zip -d pres

      - uses: actions/configure-pages@v4

      - uses: actions/upload-pages-artifact@v3
        with:
          path: pres

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
